### ISSUE TITLE
install error due to HELM client and server

### ISSUE THREAD

**Issue by rushins** [rchakode/kube-opex-analytics#11]
hello

got error while installing with HELM

helm upgrade --install kube-opex-analytics --namespace=kube-opex-analytics helm/kube-opex-analytics/
UPGRADE FAILED
ROLLING BACK
Error: incompatible versions client[v2.13.0] server[v2.12.0]
Error: UPGRADE FAILED: incompatible versions client[v2.13.0] server[v2.12.0]

any idea

**Comment by rchakode** [comment]
Hi,
The error messages seem to indicate that your version of helm client (2.13.0) is greater than the version of the server/tiller (2.12.0).

I think that by installing helm client 2.12.0, it should work.

**Comment by rchakode** [comment]
Hi @rushins,
Did you find a solution for this problem? Let's know so we can close the issue.

**Comment by rchakode** [comment]
can't be reproduced.
