### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by judexzhu** [rchakode/kube-opex-analytics#13]
Hi 

I tried to install kube-opex-analytics via helm in my kubernetes cluster.

but get an error

```
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "backend.py", line 639, in create_metrics_puller
    k8s_usage.extract_pod_metrics( pull_k8s('/apis/metrics.k8s.io/v1beta1/pods') )
  File "backend.py", line 401, in extract_pod_metrics
    pod.cpuUsage += self.decode_cpu_capacity(container['usage']['cpu'])
  File "backend.py", line 285, in decode_cpu_capacity
    return int(cap_input)
ValueError: invalid literal for int() with base 10: '8001u'
```

kubernetes version is 1.11.5

Is there anything I can do about it?
![image](https://user-images.githubusercontent.com/17834225/60314277-ad1bca80-9994-11e9-8798-803e8acf23d5.png)

Thank you

**Comment by rchakode** [comment]
Hi,
Thank you for the report. 
It seems that there is a problem when parsing pod metrics with a unit that we missed to handle, that'll be fixed in the next few days.

Rodrigue

**Comment by rchakode** [comment]
Hi,
This should now be fixed in version 0.3.1 just released. 
Please try it out and let us know your feedback.

**Comment by judexzhu** [comment]
Thank you for your quick response and fix, Sir!
That's fantastic!

I didn't see any error logs right now.

but however, I don't see the chart either 

I can list all my work nodes at the bottom of the page , seems api connection is good 

but no chart is showing, any way to find out why ?

![image](https://user-images.githubusercontent.com/17834225/60382016-7d9db880-9a8f-11e9-9b10-e1736770a050.png)

**Comment by rchakode** [comment]
Nice that thinks work for you. 
Indeed you need almost an hour to have all charts, as namespace usage cost are is hourly-based.

> Don't miss to give a star to the project :)
