### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by agrushin** [rchakode/kube-opex-analytics#23]
Hi,

looks like `m` unit does not handled properly in decode_memory_capacity() function:

```Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "backend.py", line 661, in create_metrics_puller
    k8s_usage.extract_nodes(pull_k8s('/api/v1/nodes'))
  File "backend.py", line 326, in extract_nodes
    node.memAllocatable = self.decode_memory_capacity(item['status']['allocatable']['memory'])
  File "backend.py", line 273, in decode_memory_capacity
    return int(cap_value)
ValueError: invalid literal for int() with base 10: '14162554060800m'
```

as well as E, P, T, G, K analogs

https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory

**Comment by rchakode** [comment]
hi @agrushin,
Thank you to raise this issue, we're working to fix that.
A hotfix should be provided very shortly.

**Comment by rchakode** [comment]
Dear @agrushin,
I just made a hot release, can you retry and let me know if that fixes the issue please?
Please set your image version to `latest` or `0.4.1-rc1`

**Comment by agrushin** [comment]
Thanks for a fast response. 

Unfortunately, the same exception:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "backend.py", line 677, in create_metrics_puller
    k8s_usage.extract_nodes(pull_k8s('/api/v1/nodes'))
  File "backend.py", line 341, in extract_nodes
    node.memAllocatable = self.decode_memory_capacity(item['status']['allocatable']['memory'])
  File "backend.py", line 276, in decode_memory_capacity
    return int(cap_value)
ValueError: invalid literal for int() with base 10: '14162554060800m'
```

I believe this is because of .endswith() is case sensitive; json result have `m` in lower case, but function expected the upper.

**Comment by rchakode** [comment]
I see, the problem is that the documentation does not state about the case sensitivity...

**Comment by rchakode** [comment]
Can you try again please ?
The units are not considered non sensitive to case. Use version `latest`  or `0.4.1-rc2`

**Comment by rchakode** [comment]
by the way, do you think that in your `m` is for `milli` or `mega`. It's intriguing...

**Comment by agrushin** [comment]
Heh, that's interesting, it is now about case; Looks like `m` here stands for a `milli`.

Checked on c5.4xlarge AWS ec2 instance with 32gb ram onboard. `/api/v1/nodes` endpoint returns

```
{
  "capacity": "31901716Ki",
  "allocatable": "30485060812800m"
}
```

**Comment by rchakode** [comment]
sorry the issue was closed accidentally, can you try again with `latest` or `0.4.1-rc3` please?

**Comment by agrushin** [comment]
Yep - looks better, thanks!

**Comment by rchakode** [comment]
cool.
If you like the tool, don't miss to give a star :) Thank in advance.
