### ISSUE TITLE
Webserver component not working

### ISSUE THREAD

**Issue by choseh** [rchakode/kube-opex-analytics#30]
Hi,

after starting the kube-opex-analytics pod, it starts collecting metrics, but the webserver isn't responding (timeout).

root@kube-opex-analytics-785b5f8876-vcpjl:/koa# curl http://127.0.0.1:5483
[timeout]

We also had to disable the readiness and liveness probes, to get to debug. With those active, the container repeatedly restarts, because it's never healthy.

> *** Starting uWSGI 2.0.18 (64bit) on [Tue Nov 12 09:51:25 2019] ***
> compiled with version: 7.4.0 on 10 November 2019 22:22:21
> os: Linux-4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u5 (2019-08-11)
> nodename: kube-opex-analytics-785b5f8876-vcpjl
> machine: x86_64
> clock source: unix
> detected number of CPU cores: 16
> current working directory: /koa
> detected binary path: /usr/local/bin/uwsgi
> !!! no internal routing support, rebuild with pcre support !!!
> uWSGI running as root, you can use --uid/--gid/--chroot options
> *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
> your processes number limit is 1048576
> your memory page size is 4096 bytes
> detected max file descriptor number: 1048576
> lock engine: pthread robust mutexes
> thunder lock: disabled (you can enable it with --thunder-lock)
> *** RRDtool library available at 0x55b9cc4e8e10 ***
> uwsgi socket 0 bound to TCP address :5483 fd 3
> uWSGI running as root, you can use --uid/--gid/--chroot options
> *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
> Python version: 3.6.8 (default, Oct  7 2019, 12:59:55)  [GCC 8.3.0]
> Python main interpreter initialized at 0x55b9cc51a2b0
> uWSGI running as root, you can use --uid/--gid/--chroot options
> *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
> python threads support enabled
> your server socket listen backlog is limited to 100 connections
> your mercy for graceful operations on workers is 60 seconds
> mapped 145808 bytes (142 KB) for 1 cores
> *** Operational MODE: single process ***
> 2019-11-12 09:51:27,158 - kube-opex-analytics - DEBUG - {puller] collecting new metrics
> WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x55b9cc51a2b0 pid: 8 (default app)
> uWSGI running as root, you can use --uid/--gid/--chroot options
> *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
> *** uWSGI is running in multiple interpreter mode ***
> spawned uWSGI master process (pid: 8)
> spawned uWSGI worker 1 (pid: 14, cores: 1)
> /usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning,
> /usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning,
> /usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning,
> /usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning,
> /usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning,
> 2019-11-12 09:51:54,873 - kube-opex-analytics - DEBUG - [puller][sample] non-allocatable, 0.000000, 0.336612

Config Values:

> envs:
>   KOA_DB_LOCATION: /data/db
>   KOA_K8S_API_ENDPOINT: https://kubernetes.default
>   KOA_K8S_API_VERIFY_SSL: false
>   KOA_COST_MODEL: CUMULATIVE_RATIO
>   KOA_BILLING_HOURLY_RATE: 0.0
>   KOA_BILLING_CURRENCY_SYMBOL: $
>   KOA_ENABLE_DEBUG: true
>   KOA_K8S_AUTH_TOKEN: <redacted>

Anythin we can contribute to help debug this issue?

Best,
Alex

**Comment by rchakode** [comment]
Hi @choseh,
Sorry for the late reply.
Did you try to access the service through port forwarding instead?

Run this command on your local machine and open a browser at http://127.0.0.1:9080

```
kubectl -n kube-opex-analytics port-forward service/kube-opex-analytics 9080:80
```
This command assumes that you're running the service in the namespace `kube-opex-analytics`

**Comment by rchakode** [comment]
Also which version do you use?

**Comment by choseh** [comment]
We're running it in an existing k8s cluster. It's behind traefik in this case. We're on 0.4.5, same issue with prior versions.

**Comment by rchakode** [comment]
Can you please try `curl http://kube-opex-analytics/` from the pod' console (instead of using 127.0.0.1:5483)

**Comment by choseh** [comment]
root@kube-opex-analytics-69989c4b8-ppjmj:/koa# curl http://kube-opex-analytics/
^C

same thing. timeout

**Comment by choseh** [comment]
tcp        3      0 0.0.0.0:5483            0.0.0.0:*               LISTEN      0          2374429    8/uwsgi

**Comment by rchakode** [comment]
I don't know if it's related, perhaps you may try it in unprivileged mode?
Set `securityContext` to `true` in values.yaml file

**Comment by choseh** [comment]
We had that set to true before, in order to allow more debugging we switched it to false. I just set it to true again, but unfortunately this didn't change anything.

**Comment by rchakode** [comment]
How do you use traefik, as service mesh?
Perhaps you need a sidecar or additional config to make the routing works with traefik?

This is not something we're already experienced, I just make a test on GKE and everything looks good. 
Unfortunately I don't have a cluster with traefik to try to reproduce the problem in your context.

**Comment by choseh** [comment]
can you curl http://127.0.0.1:5483  from within the pod?

**Comment by choseh** [comment]
And no, we're on traefik <2.0 so no service mesh stuff yet.

**Comment by rchakode** [comment]
That's what I did in GKE :

```
kubectl run -i --tty busybox --image=busybox -- sh
wget -o - http://kube-opex-analytics.kube-opex-analytics
```
and the output is 
```
saving to 'index.html'
index.html           100% |******************************************************************************************************************************************************************************| 14604  0:00:00 ETA
'index.html' saved
/ # 
```
Everything is working fine.

**Comment by atze234** [comment]
Hi, when i run it locally in Docker Container (build with Dockerfile from master branch) with Debug Mode and token to a small test cluster im getting timeout to 127.0.0.1:5483 too. 
So seems not be related to k8s at all. My Docker Version 18.06.1-ce-rc1

**Comment by atze234** [comment]
When switching uwsgi off, back to direct call in entrypoint 
`python3 -u ./backend.py`

and call the flask app directly in backend.py
`if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5483)`

Frontend is loading for me.
So it seems to be related to uwsgi and/or the prometheus middleware part. But how to investigate that further?

**Comment by rchakode** [comment]
Hi,
@atze234 many thanks for this feedback.

@choseh are you able to try this trick? If it's confirmed that it fix the issue we'll manage to introduce it as alternative (through a startup option) in our upcoming releases.

**Comment by choseh** [comment]
hey @rchakode 
@atze234 is actually on my team and we were discussing this already today, so we're working on the same thing :) We found an alternative that offers aws billing optiona out of the box and I don't think we'll investigate any further. We can help if anyone else has the same issue though.

**Comment by rchakode** [comment]
Right, thank you for the feedback.
