### ISSUE TITLE
unable to access Dashboard using kubectl proxy

### ISSUE THREAD

**Issue by smetal1** [rchakode/kube-opex-analytics#31]
I am getting the following error while accessing the dashboard .
Error: E1114 10:59:07.848191   26072 portforward.go:400] an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod 8e17b8b61ec08320b960c1c00a32a108b1457186a8fd9fc2078688f4f26512a0, uid : exit status 1: 2019/11/14 05:29:07 socat[20928] E connect(5, AF=2 127.0.0.1:8080, 16): Connection refused

pod log: [pid: 13|app: 0|req: 28/28] 172.31.8.230 () {26 vars in 320 bytes} [Thu Nov 14 05:33:41 2019] GET / => generated 14604 bytes in 0 msecs (HTTP/1.1 200) 5 headers in 146 bytes (1 switches on core 0)

**Comment by rchakode** [comment]
Hi,
What is the port 8080 you have in your logs? 
Can you try with port forwarding?

A typical command would be:
```
kubectl -n kube-opex-analytics port-forward service/kube-opex-analytics 9080:80
```
You would then be able to access the interface using http://127.0.0.1:9080

**Comment by rchakode** [comment]
Can not reproduce it.
