### ISSUE TITLE
env variable KOA_ENABLE_PROMETHEUS_EXPORTER not correclty decoded

### ISSUE THREAD

**Issue by ccamel** [rchakode/kube-opex-analytics#32]
It appears that the environment variable `KOA_ENABLE_PROMETHEUS_EXPORTER` introduced by e5616c357e5833214350e9d8d4d3b4fa45fcc6b7 in [v0.4.6](https://github.com/rchakode/kube-opex-analytics/releases/tag/v0.4.6)  is not correctly processed.

The console output shows:
```
./entrypoint.sh: 20: [: true: unexpected operator
 * Serving Flask app "backend" (lazy loading)
```

Issue is due to the wrong shell interpreter used to execute the script. The *shebang* states to use the `bash` interpreter, but the docker build states to use `sh` in the [ENTRYPOINT](https://github.com/rchakode/kube-opex-analytics/blob/master/Dockerfile#L31) (that latter wins).

**Comment by rchakode** [comment]
Weird, missed to catch this issue during dev tests.
Will switch back the entrypoint as sh script and update the condition accordingly.

**Comment by rchakode** [comment]
can you try witrh version 0.4.7 just released please?

**Comment by ccamel** [comment]
It works fine! Great :wink:
