### ISSUE TITLE
Grafana dashboard explanation.

### ISSUE THREAD

**Issue by imran-baig-se** [rchakode/kube-opex-analytics#36]
hi team, can u just explain me the below grafana. what is it referring to is it cost or it is resource utilization unable to understand the data here.

![image](https://user-images.githubusercontent.com/25133298/80206123-dcdf4180-863c-11ea-9989-c4e8da902a2d.png)

Thanks

**Comment by rchakode** [comment]
Hi @imran-baig-se,
When you start an instance of kube-opex-analytics, you choose with the config variable `COST_MODEL` (see Readme) if you want to handle costs or utilization (not both at a time).

So all the charts you have on the graphs are all based on the unit selected (cost, cumulative utilization, or utilization ratio).

**Comment by imran-baig-se** [comment]
@rchakode thanks for a quick response how do I verify which config am on and to switch to COST_MODEL

so is it  COST_MODEL  or  Cumulative 

![image](https://user-images.githubusercontent.com/25133298/80214314-aa891080-864b-11ea-926a-07a8bf177fe4.png)
![image](https://user-images.githubusercontent.com/25133298/80214320-ae1c9780-864b-11ea-97da-bbc66989e895.png)


Thanks

**Comment by rchakode** [comment]
To switch cost model you need to restart the container with the appropriate configuration variables (see https://github.com/rchakode/kube-opex-analytics#cost-models).

The unit of usage is not more displayed on the dashboard, but you can call the endpoint `/static/data/backend.json` of your instance to retrieve this information.

**Comment by rchakode** [comment]
Hi @imran-baig-se,
As of version v20.03.3 just released, the usage accounting unit is now displayed on the dashboard.
