### ISSUE TITLE
Unable to run kube-opex-analytics container in userns enabled system

### ISSUE THREAD

**Issue by Pratima** [rchakode/kube-opex-analytics#40]
Refer [Debugging Container ID Cannot Be Mapped to Host ID Error](https://circleci.com/docs/2.0/high-uid-error/)
This is blocking us from using kube-opex-analytics. Could the `RUNTIME_USER_UID` be changed to a number between 0-65535.

**Comment by rchakode** [comment]
this feature is now released in version [v20.03.3](Kubernetes Opex Analytics v20.03.3).
