### ISSUE TITLE
Is there no way to have KOA_BILLING_HOURLY_RATE be dynamically updated as cluster usage increases and decreases using autoscaler?

### ISSUE THREAD

**Issue by alexmnyc** [rchakode/kube-opex-analytics#49]
Is there no way to have KOA_BILLING_HOURLY_RATE be dynamically updated as cluster usage increases and decreases using autoscaler?

**Comment by rchakode** [comment]
Hi @alexmnyc,
Can we have more details about how you want to handle this setting dynamically?

Indeed, currently if you've deployed kube-opex-analytics through the helm chart as statefulset with a persistent volume,  you just have to edit the KOA_BILLING_HOURLY_RATE parameter and the pod will be restarted with the new value.

**Comment by alexmnyc** [comment]
Not sure how one would calculate it. But isn't that what kubecost does?

The cluster cost coule be calculated using billing API perhaps, maybe use tagging api to look for a specific cluster tag for all resources and then calculate running cost at that minute interval or something. It obviously won't be a flat value over time as an autoscaled cluster will have more resources and then less based on load I suppose. It's more of a question how people go about using it with a dynamic size cluster

**Comment by rchakode** [comment]
I see the point, we'll consider it for a future version.

Thank you to have highlighted that.

**Comment by rchakode** [comment]
Feature in progress : see PR #62
