### ISSUE TITLE
Allows accounting based on resource.requests instead real usage

### ISSUE THREAD

**Issue by caruccio** [rchakode/kube-opex-analytics#64]
**Is your feature request related to a problem? Please describe.**
My users are charge by requested resources instead used resources. For example, when someone asks for 1Gi and ends up using 500Mi, it will be charged by 1Gi.

**Describe the solution you'd like**
Be able to calculate usage by allocated resources instead used resources.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by rchakode** [comment]
Hi @caruccio ,
Thank you to report this.
Make sense, we'll investigue how to integrate this feature.

**Comment by caruccio** [comment]
Hey @rchakode. Thanks for your reply.
That's an elegant solution. However, since classes `K8sUsage` and `Rrd` are only "connected" by the databases, I can't see how to correlate `usage` and `rf` other than using its timestamps.

**Comment by rchakode** [comment]
yes, timestamps is the way to go if you follow this path:.
 * on the hand, you will have a map of usage accounting as `[resource_type][namespace][timestamp] => usage` 
 * on the other hand, you will have a map of request efficiency as `[resource_type][namespace][timestamp] => rf`  

Then you can compute a map of request accounting as `[resource_type][namespace][timestamp] => usage/rf` 

Does this make sense for you?

**Comment by caruccio** [comment]
Hey @rchakode.

The issue is that usage accounting stores ratios only, not absolute resource values. Since cluster capacity is lost on dumping, it can't be used on a cluster with autoscaling on (which is a must have for my case).

No need for high prio implementation for now. I'm doing an investigation only.

**Comment by rchakode** [comment]
Ok. 
But the point I want to understand : how do you want to charge requests without using ratio?

Do you mean, for example, you want to charge 1GB of memory at a given rate, instead of charging a portion of memory based on requests ?

**Comment by caruccio** [comment]
Hey @rchakode. Sorry for the delayed response.

After some consideration, the current method of charging for a ratio of the total requested memory is enough for my needs.
Just submitted PR #66. Hope it's ok to merge.

Any question please feel free to reach.

**Comment by caruccio** [comment]
Closed by #66
