### ISSUE TITLE
Add support for a cost model

### ISSUE THREAD

**Issue by luisdavim** [rchakode/kube-opex-analytics#7]
We could provide a config file where we assign a dollar amount to the CPU and memory units and then we can have dashboards showing how much money is being used where.

**Comment by rchakode** [comment]
Hi @luisdavim,
Thank to report this, what looks interesting as feature. 
This raises me a question, how do you think the cost calculation regarding both cpu and memory? A aggregated cost? Or cost for each resource?

**Comment by luisdavim** [comment]
Per resource would be nice.

**Comment by rchakode** [comment]
hi @luisdavim,
This feature is under development is would be published with the next release, expected by the end of the month.

**Comment by luisdavim** [comment]
Awesome, thanks.

**Comment by rchakode** [comment]
hi @luisdavim, please give a try to version [v0.2.0](https://github.com/rchakode/kube-opex-analytics/tree/v0.2.0) just [released](https://github.com/rchakode/kube-opex-analytics/tree/v0.2.0) and let me know. 

It's mentioned in the release notes, but I want to said it again. Thank you for all your input (feedback/code/...). Your contributions are always welcome ;)
