### ISSUE TITLE
what's mean non-allocatable resources ?

### ISSUE THREAD

**Issue by watchmen1992** [rchakode/kube-opex-analytics#75]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rchakode** [comment]
Hi @watchmen1992 ,

Non allocatable resources are capacities reserved for operating systems and Kubernetes components. 
Some distributions and home-made Kubernetes setup may not have  reserved capacities.

**Comment by rchakode** [comment]
Non-allocatable capacities are also referred to as reserved capacities: https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/

**Comment by rchakode** [comment]
Without a follow up, we will close the issue.
