### ISSUE TITLE
Ingress apiVersion extensions/v1beta1 is deprecated

### ISSUE THREAD

**Issue by ppodbielski** [rchakode/kube-opex-analytics#86]
**Describe the bug**
apiVersion: extensions/v1beta1 is deprecated

**To Reproduce**
1. check /manifests/helm/templates/ingress.yaml file

**Expected behavior**
migrate to networking.k8s.io/v1

**Comment by rchakode** [comment]
Hi @ppodbielski ,
Thank you to report this.
We'll fix that.

**Comment by rchakode** [comment]
Fixed in main
